security:
    password_hashers:
        App\Entity\Utilisateur:
            algorithm: auto

    providers:
        utilisateur_provider:
            entity:
                class: App\Entity\Utilisateur
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: utilisateur_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/connexion, roles: PUBLIC_ACCESS }
        - { path: ^/inscription, roles: PUBLIC_ACCESS }
        - { path: ^/mot-de-passe-oublie, roles: PUBLIC_ACCESS }
        - { path: ^/reinitialiser-mot-de-passe/.*, roles: PUBLIC_ACCESS }
        - { path: ^/anecdote, roles: PUBLIC_ACCESS }
        - { path: ^/recherche, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/css, roles: PUBLIC_ACCESS }
        - { path: ^/js, roles: PUBLIC_ACCESS }
        - { path: ^/profil, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/modifier-profil, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/deconnexion, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/changer-photo, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/ajouter-recette, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/supprimer-recette/.*, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/modifier-recette/.*, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/recette/.*, roles: PUBLIC_ACCESS }
        - { path: ^/recette/.*, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/admin/.*, roles: [ROLE_ADMIN] }



        - { path: ^/, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
